name: Periodically scan latest image for vulnerabilites
on:
  schedule:
    - cron: "1 3 * * 5"
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: dschanoeh/healthbuddy:latest